name: paged_vertical_calendar
description: A simple paginated framework for implementing calendar based interfaces.
homepage: https://github.com/casvanluijtelaar/paged_vertical_calendar
repository: https://github.com/casvanluijtelaar/paged_vertical_calendar
version: 1.1.5

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  infinite_scroll_pagination: ^3.2.0
  week_of_year: ^2.0.0
  sticky_headers: ^0.3.0+2
  flutter_sticky_header: ^0.6.4
  intl: ^0.17.0
  scroll_to_index: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
